### ISSUE TITLE
this.ui should be optional?

### ISSUE THREAD

**Issue by bakerac4** [ember-fastboot/ember-fastboot-server#14]
```
DEBUG: -------------------------------
DEBUG: Ember           : 2.3.1
DEBUG: Ember Data      : 2.3.3
DEBUG: Model Fragments : 2.1.0
DEBUG: -------------------------------
/login
TypeError: Cannot read property 'writeLine' of undefined
    at FastBootServer.log (/node_modules/ember-fastboot-server/lib/server.js:32:10)
    at FastBootServer.handleSuccess (/node_modules/ember-fastboot-server/lib/server.js:46:8)
    at success (/node_modules/ember-fastboot-server/lib/server.js:85:14)
    at Timer.listOnTimeout (timers.js:119:15)`
```

This.ui comes from options.ui. (server.js line 20)

A) I have not found a reference to ui in the docs, so I'm not sure what to pass in.
B) According to #13, I should pass in distPath to new FastBootServer and nothing else
```
var server = new FastBootServer({
     distPath: '../ember-test-app/fastboot-dist'
});
```
Should UI be completely optional?

**Comment by bakerac4** [comment]
For anyone that needs to get by this, I added this

```
var server = new FastBootServer({
     distPath: '../ember-test-app/fastboot-dist',
     ui: {
            writeLine: function(info) {
                console.log(info);
            }
        }
});
```

And I was able to get by the error above. Still unsure whether or not it should be optional or not.

**Comment by bakerac4** [comment]
Would you guys accept a pull request adding in

```
ui: {
    writeLine: function(info) {
        console.log(info);
    }
}
```
as a backup if options.ui is not passed in?

**Comment by rwjblue** [comment]
Yeah, seems good (though I'm curious why UI isn't being passed in)...

**Comment by bakerac4** [comment]
@rwjblue Can you explain to me where UI should be coming from? I can't seem to find it in any documentation. I can probably figure out whats going from there and report back. I'll still do the pull request, since it seems like it should be optional since its coming from options.

**Comment by bakerac4** [comment]
#18 added to handle this issue
