### ISSUE TITLE
Use native vm instead of contextify on Node.js v0.12 or later

### ISSUE THREAD

**Issue by okuryu** [ember-fastboot/ember-fastboot-server#35]
The https://github.com/ember-fastboot/ember-fastboot-server/pull/9 was looks great to me, but it seems to reverted at https://github.com/ember-fastboot/ember-fastboot-server/commit/dfd19f595d958a9746f9f335bb592991a1d6f69a.

I hope retrying this change again to run ember-fastboot-server on Mac and Linux more easier.

**Comment by tomdale** [comment]
@okuryu This is in now. :)

**Comment by okuryu** [comment]
Thanks a lot! :+1:
